### Cadastro de Funcionário
POST http://localhost:8080/api/auth/cadastro
Content-Type: application/json

{
  "nome": "João Silva",
  "email": "joao.silva@example.com",
  "senha": "minhaSenha123",
  "cargo": "admin"
}

### Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2ODJiM2JmNzI3YjdkZTEyMzg2MTBjMzQiLCJub21lIjoiSm_Do28gU2lsdmEiLCJjYXJnbyI6ImFkbWluIiwiZXhwIjoxNzQ4MjU3NDg0fQ.CX6RAxsWf-UNSpC-zaiz4ZfEGaDPAWKc7NN3qQCaPqo

### Login de Funcionário
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "joao.silva@example.com",
  "senha": "minhaSenha123"
}


